// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_msg_type.proto

#ifndef PROTOBUF_server_5fmsg_5ftype_2eproto__INCLUDED
#define PROTOBUF_server_5fmsg_5ftype_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace server_protocols {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_server_5fmsg_5ftype_2eproto();
void protobuf_AssignDesc_server_5fmsg_5ftype_2eproto();
void protobuf_ShutdownFile_server_5fmsg_5ftype_2eproto();


enum e_server_msg_type {
  e_mst_server_register = 0,
  e_mst_server_register_result = 1,
  e_mst_other_server_connect = 2,
  e_mst_other_server_disconnect = 3,
  e_mst_updata_servers_info = 4,
  e_mst_updata_self_info = 5,
  e_mst_transmit_msg = 6,
  e_mst_broadcast_msg = 7,
  e_mst_heartbeat = 9,
  e_mst_server_connect = 10,
  e_mst_server_connect_result = 11,
  e_mst_player_connect = 12,
  e_mst_player_disconnect = 13,
  e_mst_regedit_route_msg = 14,
  e_mst_gate_setlogic_ok = 15,
  e_mst_clear_session = 16,
  e_mst_broadcast_msg2 = 17,
  e_mst_http_command = 18,
  e_mst_get_ip = 19,
  e_mst_get_ip_result = 20,
  e_mst_maxcount = 255
};
bool e_server_msg_type_IsValid(int value);
const e_server_msg_type e_server_msg_type_MIN = e_mst_server_register;
const e_server_msg_type e_server_msg_type_MAX = e_mst_maxcount;
const int e_server_msg_type_ARRAYSIZE = e_server_msg_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_server_msg_type_descriptor();
inline const ::std::string& e_server_msg_type_Name(e_server_msg_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_server_msg_type_descriptor(), value);
}
inline bool e_server_msg_type_Parse(
    const ::std::string& name, e_server_msg_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_server_msg_type>(
    e_server_msg_type_descriptor(), name, value);
}
enum http_command_type {
  e_cmd_order = 1,
  e_cmd_recharge = 2,
  e_cmd_addlucky = 3
};
bool http_command_type_IsValid(int value);
const http_command_type http_command_type_MIN = e_cmd_order;
const http_command_type http_command_type_MAX = e_cmd_addlucky;
const int http_command_type_ARRAYSIZE = http_command_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* http_command_type_descriptor();
inline const ::std::string& http_command_type_Name(http_command_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    http_command_type_descriptor(), value);
}
inline bool http_command_type_Parse(
    const ::std::string& name, http_command_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<http_command_type>(
    http_command_type_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace server_protocols

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::server_protocols::e_server_msg_type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::server_protocols::e_server_msg_type>() {
  return ::server_protocols::e_server_msg_type_descriptor();
}
template <> struct is_proto_enum< ::server_protocols::http_command_type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::server_protocols::http_command_type>() {
  return ::server_protocols::http_command_type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_server_5fmsg_5ftype_2eproto__INCLUDED
